<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__donate_amount_flex</name>
   <tag></tag>
   <elementGuidId>ae9982bc-671e-4e1d-93a1-514ee11df199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;donate_amount_flex&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='donate_amount_flex']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Введите вашу сумму' and @placeholder = 'Другая сумма']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14a8fa7d-b844-4164-a937-d514271103ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>df063e2b-b692-430c-b7c4-d937e5b6b2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Введите вашу сумму</value>
      <webElementGuid>252fb4bf-65ae-44ed-9426-37b4b11c99f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Другая сумма</value>
      <webElementGuid>da3e494e-dfac-4577-b23e-8a9637829dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-desktop-ph</name>
      <type>Main</type>
      <value>Другая сумма</value>
      <webElementGuid>5a42f489-3ff0-4788-b9a3-fb131c96ff48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mobile-ph</name>
      <type>Main</type>
      <value>Введите вашу сумму</value>
      <webElementGuid>edb3c086-8f6c-4954-b400-e2def3a620ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>donate_amount_flex</value>
      <webElementGuid>346ea2ae-f5f5-445b-a8ec-3f3c3c6d8544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>donate_amount_flex</value>
      <webElementGuid>49fc9a80-b51a-41a3-877a-5b91cd132c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>8800b48b-5e35-4c5e-a2c2-98afbdfef444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ffd33958-a875-4445-a8e0-477cd2ad2f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999999</value>
      <webElementGuid>83fbd052-77de-4f1b-aee1-29ffe1870fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Другая сумма</value>
      <webElementGuid>5ce18232-a797-477a-90dc-bcbad58ebfb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-pf-112-star-form&quot;)/div[@class=&quot;currency-tab currency-rub&quot;]/div[@class=&quot;section section--amount&quot;]/div[@class=&quot;section__fields amount&quot;]/div[@class=&quot;amount__figure star-swiper no-swipe only-one-item show-left-arrow&quot;]/div[@class=&quot;full-list&quot;]/div[@class=&quot;swiper-item flex-amount-item selected focus&quot;]/div[@class=&quot;swiper-item-inner&quot;]/input[@class=&quot;donate_amount_flex&quot;]</value>
      <webElementGuid>82991d48-f138-4955-af93-9bbda003664b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='donate_amount_flex']</value>
      <webElementGuid>f49e4ac6-1507-459c-90dc-5644f4eed41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-112-star-form']/div[3]/div[2]/div[2]/div/div[3]/div[9]/div/input</value>
      <webElementGuid>5b7a4f20-c108-44b9-abd7-3bf529922104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>6a11e92c-bc32-41a0-92df-e29fc2121c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @title = 'Введите вашу сумму' and @placeholder = 'Другая сумма' and @name = 'donate_amount_flex']</value>
      <webElementGuid>8553be61-a4f2-4d1a-b98b-c948033b055b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
