<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__leyka_donor_name</name>
   <tag></tag>
   <elementGuidId>2a844e77-356d-473e-85bf-31d7eecb20e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-2083719983</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leyka-2083719983']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'leyka_donor_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3b1769f-995c-45f9-a91a-fa5edc2ee795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-2083719983</value>
      <webElementGuid>481764a0-72bf-415f-9205-21b5a3124f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b76e97ca-8e47-4ce4-8298-c5ccafe10f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_donor_name</value>
      <webElementGuid>5bd4ef89-25bb-47dd-b528-fc2517572a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0aa5e71d-3577-4590-9529-e467b08af83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-2083719983&quot;)</value>
      <webElementGuid>576f3907-afbe-45d7-a2ea-77b2dc9b96d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-2083719983']</value>
      <webElementGuid>2097b221-b84a-4c78-aeae-8ebcd8b04eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-112-star-form']/div[3]/div[4]/div[2]/div[2]/div/input</value>
      <webElementGuid>b0fca2ca-6083-4ddd-b028-71a72ffe7129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/input</value>
      <webElementGuid>18c9ec79-eddb-4085-b48c-0150f40c988b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'leyka-2083719983' and @type = 'text' and @name = 'leyka_donor_name']</value>
      <webElementGuid>24eee2cf-91a3-41a9-ac53-cb8095fab712</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
