<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__leyka-default-submit</name>
   <tag></tag>
   <elementGuidId>c348411b-cfca-47a0-9f0c-63a557aea192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.leyka-default-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Пожертвовать']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>429231a4-e900-44fe-b97a-0f5b40a7625c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ba9e4708-e302-4cd9-a24a-a0889a7e06fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leyka-default-submit</value>
      <webElementGuid>890ad173-18b3-42cf-8807-5e43ee6cb607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Пожертвовать</value>
      <webElementGuid>73349dd8-aa4e-47e6-b081-663ce41c1661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-pf-112-star-form&quot;)/div[@class=&quot;currency-tab currency-rub&quot;]/div[@class=&quot;section section--person&quot;]/div[@class=&quot;section__fields donor&quot;]/div[@class=&quot;donor__submit&quot;]/input[@class=&quot;leyka-default-submit&quot;]</value>
      <webElementGuid>e467877d-6b99-4af2-8fdc-0600796be992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Пожертвовать']</value>
      <webElementGuid>59edac2b-0bef-4050-8fad-2a0b79c92fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-112-star-form']/div[3]/div[4]/div[2]/div[4]/input</value>
      <webElementGuid>848316da-8b57-4f08-ab30-8bb308792c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>167d6311-b588-4b8f-b27a-a1241ce072cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>1c0c88a2-e2df-412f-a196-56f2d2ad6670</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
