<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_,_leyka_data</name>
   <tag></tag>
   <elementGuidId>1cc7d937-ab66-40ad-8694-8586dbff1ac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-3992788573</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/article/div/main/div[1]/div/div[1]/form/div[3]/div[4]/div[2]/div[5]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96fd51dd-d225-4208-bde7-ee8290368429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ef01577-fe7b-4080-8ac1-2b077570e799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-3992788573</value>
      <webElementGuid>7340c6fe-be21-4438-be36-e4b6430b9e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_data</value>
      <webElementGuid>1b7cc9ac-ede4-4a40-9dce-bf4220c5c9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4a600031-cf63-4835-917d-2e62750080f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inputmask</name>
      <type>Main</type>
      <value>'mask': '99.99.9999'</value>
      <webElementGuid>ec76cdf8-1ec3-47be-8d7e-8f79881a4d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>__.__.____</value>
      <webElementGuid>230a13db-19f8-49f7-84b9-adec2fbb98cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>517a73f8-0049-4d68-8ced-d7c13cba8ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-3992788573&quot;)</value>
      <webElementGuid>731a5dd5-a622-4708-9641-a22bbeff9199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-3992788573']</value>
      <webElementGuid>3aafd89b-445f-4229-8b5d-d89e93e95f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-148-need-help-form']/div[3]/div[4]/div[2]/div[5]/div/input</value>
      <webElementGuid>f445f2f9-545e-4cf3-ac48-ac0c09cac822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>7cd82e0b-ecc4-4be6-b0f6-ea5bddeeed54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leyka-3992788573' and @name = 'leyka_data' and @placeholder = '__.__.____']</value>
      <webElementGuid>1749b51a-3dd3-4705-8618-c5e37e45d4d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
