<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>a99910a6-8dab-4f4b-a225-7b38f2515eda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='toplevel_page_leyka']/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fdaf55c5-32a8-4798-aaf9-06c33fb38e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>admin.php?page=leyka_help</value>
      <webElementGuid>e2e45ca1-8b18-4b04-951f-5a7568413acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Помощь</value>
      <webElementGuid>80031343-74d0-4df1-b3c5-736e30219ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toplevel_page_leyka&quot;)/ul[@class=&quot;wp-submenu wp-submenu-wrap&quot;]/li[8]/a[1]</value>
      <webElementGuid>3d060492-0927-4060-aa17-b75a5488ac9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='toplevel_page_leyka']/ul/li[8]/a</value>
      <webElementGuid>0c2eaed0-bb4a-4f6d-a3a0-1e2ce50e8ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Помощь')]</value>
      <webElementGuid>e254eb7a-be40-4c25-b1ff-2b795c7a6fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Настройки'])[3]/following::a[1]</value>
      <webElementGuid>a44dc3a3-c0d6-4e5b-99ed-a4637af2bccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Доноры'])[1]/following::a[2]</value>
      <webElementGuid>9eb48670-6585-4fd2-99dc-968ab1297464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Кандинский'])[1]/preceding::a[1]</value>
      <webElementGuid>db7aa96b-2df1-4c21-a963-2730e41f1d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Настройки темы'])[1]/preceding::a[2]</value>
      <webElementGuid>927eeb0e-14ed-4cad-bd3f-3acd494f35c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Помощь']/parent::*</value>
      <webElementGuid>cd0a1264-74c8-4af4-a83b-5813fa136c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'admin.php?page=leyka_help')]</value>
      <webElementGuid>705b4e09-e1fb-452a-8b60-038c2cd62e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[19]/ul/li[8]/a</value>
      <webElementGuid>2a81601a-474d-4af4-b3a6-a22538c23248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'admin.php?page=leyka_help' and (text() = 'Помощь' or . = 'Помощь')]</value>
      <webElementGuid>360f9d53-39de-4d63-a1c6-c608ff0d67b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
