<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>48d9056d-a585-441f-8819-470e154beb9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='toplevel_page_leyka']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>435d35de-54f7-4105-9c2e-3e0f338d7995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>admin.php?page=leyka_donations</value>
      <webElementGuid>fa04f70f-bd16-4ed1-9887-eebce2d2cee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Пожертвования</value>
      <webElementGuid>c88f76b6-9a0a-44ff-b859-f5927a833b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toplevel_page_leyka&quot;)/ul[@class=&quot;wp-submenu wp-submenu-wrap&quot;]/li[4]/a[1]</value>
      <webElementGuid>c3cf0dda-0479-4d44-a1d1-e3880bc6ca81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='toplevel_page_leyka']/ul/li[4]/a</value>
      <webElementGuid>fee51197-12c8-4800-84f4-cc267fb2cc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Пожертвования')]</value>
      <webElementGuid>da373770-850e-4d93-8672-dc9d1a55ab8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Кампании'])[1]/following::a[2]</value>
      <webElementGuid>bfd99fdd-5f98-4db8-a7e7-ce750245edc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Панель управления'])[1]/following::a[3]</value>
      <webElementGuid>237675c3-8898-4f6e-ac44-4e4df7dd268b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Рекуррентные подписки'])[1]/preceding::a[2]</value>
      <webElementGuid>56b40f66-ac81-4dfc-89f0-4c52f9996c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Доноры'])[1]/preceding::a[3]</value>
      <webElementGuid>2e78028a-5b8b-400a-80b3-f7006ccdcb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Пожертвования']/parent::*</value>
      <webElementGuid>ee0778e1-0da2-4415-a0ce-52b7a8effbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'admin.php?page=leyka_donations')]</value>
      <webElementGuid>14cc1673-6568-4434-bdea-4ca06ecb2be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[19]/ul/li[4]/a</value>
      <webElementGuid>b88a249d-3d2b-4f7e-8dbe-f4011a1892b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'admin.php?page=leyka_donations' and (text() = 'Пожертвования' or . = 'Пожертвования')]</value>
      <webElementGuid>60f98244-ea0b-4fe7-8dbd-0a3a7b39bfcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
