<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>e515f7f3-e874-493d-81e2-cb431460e01c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='toplevel_page_leyka']/ul/li[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8247ffab-00e8-4cf4-9a49-10434adf3eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>admin.php?page=leyka_settings</value>
      <webElementGuid>66d3007c-22e3-4b3b-ad03-9efd9ca2cebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Настройки</value>
      <webElementGuid>6b5a2024-e727-4b95-a738-53b86c784311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toplevel_page_leyka&quot;)/ul[@class=&quot;wp-submenu wp-submenu-wrap&quot;]/li[7]/a[1]</value>
      <webElementGuid>060d48a6-d8fa-4129-b77d-7147ee2853a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='toplevel_page_leyka']/ul/li[7]/a</value>
      <webElementGuid>59b43ffd-c9e0-43a1-ad85-41d20d4f2d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Настройки')]</value>
      <webElementGuid>b05db3a4-007d-4e5c-8eff-ba9f29095013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Доноры'])[1]/following::a[1]</value>
      <webElementGuid>e69da68c-8bc0-4d99-b41f-4dc3961d58f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Рекуррентные подписки'])[1]/following::a[2]</value>
      <webElementGuid>dab58c04-fc63-4f47-9ff7-af9794511bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Помощь'])[1]/preceding::a[1]</value>
      <webElementGuid>157ca464-e828-4daf-a9eb-d5be755b894e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Кандинский'])[1]/preceding::a[2]</value>
      <webElementGuid>96a9bc23-ad48-42ca-90a7-0ad76b0cff94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'admin.php?page=leyka_settings')]</value>
      <webElementGuid>4b077b7d-529e-43bc-b445-04d45b2ab2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[19]/ul/li[7]/a</value>
      <webElementGuid>9b36325d-ce09-40d6-a776-4c79c04c9f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'admin.php?page=leyka_settings' and (text() = 'Настройки' or . = 'Настройки')]</value>
      <webElementGuid>ec941d33-c1ae-4d18-ad3f-549ed50bc1f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
