<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_2_merchandise-image</name>
   <tag></tag>
   <elementGuidId>537473f4-fddc-4d2f-827a-c43c046624b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.merchandise-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='leyka-pf-127-star-form']/div[3]/div[3]/div[2]/div/div/ul/li/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bc075368-608b-44d4-bb3c-9762cbd0b8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>merchandise-image</value>
      <webElementGuid>841b3455-9dab-4d30-80e5-3f28c84eb66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://kandinsky-wordpress-20.tw1.ru/wp-content/uploads/2022/07/partner-3.png</value>
      <webElementGuid>85011b4c-65ee-4a37-a5a0-7410bb446a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Подарок 2</value>
      <webElementGuid>668a2c29-2c97-4700-a624-c75577c3e487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-pf-127-star-form&quot;)/div[@class=&quot;currency-tab currency-rub&quot;]/div[@class=&quot;section section--merchandise&quot;]/div[@class=&quot;section__fields merchandise-grid&quot;]/div[@class=&quot;lSSlideOuter&quot;]/div[@class=&quot;lSSlideWrapper usingCss&quot;]/ul[@class=&quot;merchandise-swiper lightSlider lSSlide lsGrab&quot;]/li[@class=&quot;merchandise-item active&quot;]/img[@class=&quot;merchandise-image&quot;]</value>
      <webElementGuid>1905b3a8-39cf-4031-a2a6-5b9b33ce0dfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-127-star-form']/div[3]/div[3]/div[2]/div/div/ul/li/img</value>
      <webElementGuid>2f9ab7c8-548e-460b-bfaa-97c9dae762fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Подарок 2']</value>
      <webElementGuid>09bf8332-0095-45f4-b991-cf1f0885d013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/img</value>
      <webElementGuid>5dbf8be2-052c-42d9-b5ad-2351e73a6124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://kandinsky-wordpress-20.tw1.ru/wp-content/uploads/2022/07/partner-3.png' and @alt = 'Подарок 2']</value>
      <webElementGuid>c77f9c42-078f-4b4e-b3bd-5da26832ea2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
