<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email_leyka_donor_email</name>
   <tag></tag>
   <elementGuidId>535d0bfd-c2c1-4b4c-86c7-dc03d5e94671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-860686658</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leyka-860686658']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'leyka_donor_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bfc2e6a-ea82-466c-b240-468bf44b954d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c75c248e-153b-4da5-ba23-e643dc7b8022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-860686658</value>
      <webElementGuid>18bc5037-6434-479f-8b34-d2ec10abdd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_donor_email</value>
      <webElementGuid>9ffc50ed-f71c-4561-aa52-1f5708acd394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6e9cc965-5fe0-464a-855b-db3558a50c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-860686658&quot;)</value>
      <webElementGuid>f218adad-5695-4f0b-92fd-0ffe7fc2e485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-860686658']</value>
      <webElementGuid>c9b9cdff-cff1-455c-9f0f-ac854fbcee34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-118-star-form']/div[3]/div[4]/div[2]/div/div/input</value>
      <webElementGuid>696e4452-37c8-48b4-933b-def159bf0154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>8c9a76e9-8f19-41e3-82b3-95f0488cb871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leyka-860686658' and @name = 'leyka_donor_email']</value>
      <webElementGuid>de492c85-bf42-4338-a99f-ba5aef7b60be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
