<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__leyka_donor_name</name>
   <tag></tag>
   <elementGuidId>0c0e8187-6438-446d-aed3-f7f9de7c45c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-1046137685</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leyka-1046137685']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'leyka_donor_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ba472f6-51b6-41a9-a4fe-f8256bd6546c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-1046137685</value>
      <webElementGuid>1825b647-1f85-4115-ba78-5654c68470f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>337aba45-51e1-4d4b-9a31-17bcfce3a0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_donor_name</value>
      <webElementGuid>5bb72463-9c33-4c72-8f46-c88c2943ba29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>04a51a9c-a7b2-45b9-821f-09ca6bab0a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-1046137685&quot;)</value>
      <webElementGuid>20b77c67-cb65-412d-9f45-6ba3c6e7d6a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-1046137685']</value>
      <webElementGuid>0aaa2fff-e8d7-4428-96ea-e0a952d3047a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-118-star-form']/div[3]/div[4]/div[2]/div[2]/div/input</value>
      <webElementGuid>738cf9ab-8fec-4e62-9a0b-217c65fe4382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/input</value>
      <webElementGuid>126a1bd2-2ec1-4c36-9ccf-a4389087f60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'leyka-1046137685' and @type = 'text' and @name = 'leyka_donor_name']</value>
      <webElementGuid>395d7035-2a30-4159-9b84-6df10bae3bd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
