<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>08b475ca-c9a5-4018-aa4f-5c67436761be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'это текст' or . = 'это текст')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.donor__textfield-label.donor__text_field-label.leyka_eto-tekst-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/article/div/main/div[1]/div/div[1]/form/div[3]/div[5]/div[2]/div[3]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dd42377c-8156-4685-9eb4-881c232e4af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>donor__textfield-label donor__text_field-label leyka_eto-tekst-label</value>
      <webElementGuid>61f28fa2-6255-46f8-9ceb-ff8e58356a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>это текст</value>
      <webElementGuid>bff84f48-b5a8-470f-8c73-76d6d3897667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-pf-118-star-form&quot;)/div[@class=&quot;currency-tab currency-rub&quot;]/div[@class=&quot;section section--person&quot;]/div[@class=&quot;section__fields donor&quot;]/div[@class=&quot;donor-additional-field donor__textfield donor__textfield--text donor__textfield--eto-tekst required&quot;]/div[@class=&quot;leyka-star-field-frame&quot;]/label[1]/span[@class=&quot;donor__textfield-label donor__text_field-label leyka_eto-tekst-label&quot;]</value>
      <webElementGuid>a6066d52-42dc-4af0-9586-1bbfb723a78b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-118-star-form']/div[3]/div[4]/div[2]/div[3]/div/label/span</value>
      <webElementGuid>fca50df9-ce4a-4045-b4c0-3a70a691561e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Укажите ваше имя'])[1]/following::span[1]</value>
      <webElementGuid>d4e743dc-9ff1-4ef7-937c-e1c4e6fe6314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Имя и Фамилия'])[1]/following::span[2]</value>
      <webElementGuid>a1127064-cb8e-4049-9dd6-4d7dcd715fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='телефон'])[1]/preceding::span[2]</value>
      <webElementGuid>5cfdf263-5fff-43a4-a9fd-d4598ae5ca51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='дата'])[1]/preceding::span[4]</value>
      <webElementGuid>a9bf8326-ee45-4b44-a26d-36adf7b332b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='это текст']/parent::*</value>
      <webElementGuid>1214d10a-e002-4c42-b62e-49e3770d38ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/label/span</value>
      <webElementGuid>2c550a36-150c-42f1-8d73-fc920e699fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'это текст' or . = 'это текст')]</value>
      <webElementGuid>c6b5c4a2-9574-497b-9165-e1eaca0d4d00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
