<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__leyka-default-submit</name>
   <tag></tag>
   <elementGuidId>2e888e7d-bbd6-41c6-8bbf-fa0aacb40469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.leyka-default-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Пожертвовать']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94d5e3ce-beb5-4866-85fa-fc236335360e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2b17ede8-5755-47d0-8429-1602bc802bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leyka-default-submit</value>
      <webElementGuid>51b35b83-8bd3-4d54-b9d4-71734654abba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Пожертвовать</value>
      <webElementGuid>32259ead-84c2-4c76-8e32-a86b9b869439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-pf-112-star-form&quot;)/div[@class=&quot;currency-tab currency-rub&quot;]/div[@class=&quot;section section--person&quot;]/div[@class=&quot;section__fields donor&quot;]/div[@class=&quot;donor__submit&quot;]/input[@class=&quot;leyka-default-submit&quot;]</value>
      <webElementGuid>9a27ab31-5262-4549-8c6c-62cac2f8da65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Пожертвовать']</value>
      <webElementGuid>6e623b4e-6caf-4756-8435-1ef0b9d545fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-112-star-form']/div[3]/div[4]/div[2]/div[4]/input</value>
      <webElementGuid>8bd13841-f19b-4f8e-9458-95f1ba05b6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>13e38eaf-7f59-4ba5-a34b-38a5af095b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>11182322-98ee-4804-b5fa-742a58d880d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
