<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email_leyka_donor_email</name>
   <tag></tag>
   <elementGuidId>fdc8eb8e-03d0-493f-835c-baff90a48f39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-3678723975</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leyka-3678723975']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'leyka_donor_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93b85ef8-cd84-4de5-9898-64a0b9247794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00f7ece8-7c21-4303-a7e3-4034da194606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-3678723975</value>
      <webElementGuid>2fdfa2aa-f165-4637-8920-80cf7bca4b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_donor_email</value>
      <webElementGuid>32bfab09-aa9d-425b-bbe8-55e67ed67eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1f6fa540-7c6b-4478-9e05-779691ee55de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-3678723975&quot;)</value>
      <webElementGuid>cdd74bff-32f0-400f-9659-4129281e5139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-3678723975']</value>
      <webElementGuid>7273ca2a-e0d3-4959-b362-a4c720daeaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-112-star-form']/div[3]/div[4]/div[2]/div/div/input</value>
      <webElementGuid>98ef0b7a-ec70-40be-bb3e-75778b4ed3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>acfad7f9-0cf3-4458-8a6a-e77794e8c105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leyka-3678723975' and @name = 'leyka_donor_email']</value>
      <webElementGuid>52afa8f6-750d-48ef-b2b0-122b88bbce85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
