<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__leyka_donor_email</name>
   <tag></tag>
   <elementGuidId>c7e79901-936e-4fbf-86a7-f889edc6ce47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-2354078832</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leyka-2354078832']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d575067-6da0-4447-a41b-d6399c524d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c52501c8-2461-4c9b-8291-038a0aac9b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-2354078832</value>
      <webElementGuid>f922f0b2-ac13-4b14-8e32-17232a3a86f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_donor_email</value>
      <webElementGuid>7bc2fea4-33bf-40ee-843b-3a45676468cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f49c9b0b-c008-4c5a-acc4-67961fc01f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ваш email</value>
      <webElementGuid>39a0c776-6031-44c4-ae32-58dc038fc26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-2354078832&quot;)</value>
      <webElementGuid>3aa1fea6-6012-43a8-a75c-5fc472d33782</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-2354078832']</value>
      <webElementGuid>bb749599-8565-45d7-bc24-f1b3a3a34062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-141-need-help-form']/div[3]/div[4]/div[2]/div/label/input</value>
      <webElementGuid>ebc0ffeb-3d2f-4215-9221-2996ab946a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/label/input</value>
      <webElementGuid>52acc2ba-8308-4ec4-a72f-57ffba62dc5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leyka-2354078832' and @name = 'leyka_donor_email' and @placeholder = 'Ваш email']</value>
      <webElementGuid>3dd5fb21-f910-4c45-b0d5-7da707ab963d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
