<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__leyka-default-submit</name>
   <tag></tag>
   <elementGuidId>e0f8b001-4f4a-4212-b471-0329727579bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.leyka-default-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Пожертвовать']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58a04734-f2ae-4bb3-9d93-a8b61adc7495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>189e485e-052d-4ffd-be7d-44a1dd2a4da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leyka-default-submit</value>
      <webElementGuid>bb54ef21-8850-440d-80e8-10e5ea643516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Пожертвовать</value>
      <webElementGuid>35834571-4caf-43d3-9126-b19dab504ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-submit-text-template</name>
      <type>Main</type>
      <value>Оформить ежемесячное пожертвование в #DAILY_ROUBLE_AMOUNT# ₽</value>
      <webElementGuid>e84b0fcd-2b1b-47a8-99e7-b21b76920746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-pf-141-need-help-form&quot;)/div[@class=&quot;currency-tab currency-rub&quot;]/div[@class=&quot;section section--agreements&quot;]/div[@class=&quot;section__fields agreements&quot;]/div[@class=&quot;donor__submit&quot;]/input[@class=&quot;leyka-default-submit&quot;]</value>
      <webElementGuid>ef87d372-fc22-45d8-860b-87e333b34a29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Пожертвовать']</value>
      <webElementGuid>6a95e0dd-4e87-4019-bc06-7d44ec1ec4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-141-need-help-form']/div[3]/div[5]/div/div[2]/input</value>
      <webElementGuid>c087160a-aa3a-499f-8f12-bdaa0fab3284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>277118e2-9812-4f3e-b4e0-636f06cecfe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>6e385a31-67f9-4845-ab5b-366c14a11936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
