<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__donate_amount_flex</name>
   <tag></tag>
   <elementGuidId>af66fbf9-df1f-4619-a995-5bc96f5c0c14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;donate_amount_flex&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/article/div/main/div[1]/div/div[1]/form/div[3]/div[1]/div[2]/div/div/label/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3725a3da-4c45-400d-bafd-43567717ac86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>194a23aa-8c7e-4b93-a191-959330623057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Введите вашу сумму</value>
      <webElementGuid>81784ed7-4586-4eee-8b19-d79b4b58ed78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Другая сумма</value>
      <webElementGuid>7cdc75ba-6377-49e3-8dae-5cc139ad43e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-desktop-ph</name>
      <type>Main</type>
      <value>Другая сумма</value>
      <webElementGuid>755f727c-fa6b-4bad-84c0-d23476a93324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mobile-ph</name>
      <type>Main</type>
      <value>Введите вашу сумму</value>
      <webElementGuid>e9dac78f-a08c-4ab0-966d-ab42ee376f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>donate_amount_flex</value>
      <webElementGuid>35a1a7f5-798c-4304-a560-75a3ce627be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>donate_amount_flex empty</value>
      <webElementGuid>dc73a051-1639-4039-a5ac-e811a927effd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e0a00f5e-3693-4e7a-9139-a39abefde291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999999</value>
      <webElementGuid>06c07022-0953-4a8e-9deb-908354a2760e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-pf-141-need-help-form&quot;)/div[@class=&quot;currency-tab currency-rub&quot;]/div[@class=&quot;section section--amount&quot;]/div[@class=&quot;section__fields amount&quot;]/div[@class=&quot;amount__figure star-swiper no-swipe only-one-item show-left-arrow&quot;]/div[@class=&quot;full-list equalize-elements-width&quot;]/label[@class=&quot;swiper-item flex-amount-item selected focus&quot;]/span[@class=&quot;swiper-item-inner empty&quot;]/input[@class=&quot;donate_amount_flex empty&quot;]</value>
      <webElementGuid>c73ac11b-5887-439c-aca8-c903f7c333ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='donate_amount_flex']</value>
      <webElementGuid>428fdca3-b008-4b4b-9409-fe7a6b4c4186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-141-need-help-form']/div[3]/div/div[2]/div/div/label/span/input</value>
      <webElementGuid>cd3d4a77-0d46-4d1f-8306-fdb3e5db80c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>393ae4d5-509c-45e7-b8f5-95a12e870d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @title = 'Введите вашу сумму' and @placeholder = 'Другая сумма' and @name = 'donate_amount_flex']</value>
      <webElementGuid>7f8fa8cb-5864-4425-a7e6-b35a4c9cb18a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
