<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email_leyka_donor_name</name>
   <tag></tag>
   <elementGuidId>1d304889-c36e-4d06-bc47-3598372bd7b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-4080763639</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leyka-4080763639']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99864f66-5da3-4cdc-a9c5-884d07532a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-4080763639</value>
      <webElementGuid>726c5bf5-26b7-4bdd-ab9d-7bd464653b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5de32d1a-f414-4b6f-8bd2-720ce9995d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_donor_name</value>
      <webElementGuid>1beb09e7-ffca-4f99-89d3-1608f01442a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d71d9540-1070-4945-bb0f-7cdfb17f110b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ваши имя и фамилия</value>
      <webElementGuid>5ad5751b-fde7-428a-9d3d-8d9671dc9457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-4080763639&quot;)</value>
      <webElementGuid>3716cd2b-6825-4e49-b170-e279d69c333b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-4080763639']</value>
      <webElementGuid>7bb34ce4-7f20-4461-b27d-b64f709314c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-141-need-help-form']/div[3]/div[4]/div[2]/div[2]/label/input</value>
      <webElementGuid>0b7c23a2-f70d-4596-a109-2abb1d416292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>9b6abd11-e880-4d8f-8ca1-0cb43809041e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'leyka-4080763639' and @type = 'text' and @name = 'leyka_donor_name' and @placeholder = 'Ваши имя и фамилия']</value>
      <webElementGuid>78bead56-6849-46a1-aa91-c75f63a51f8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
