<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_,_leyka_telefon</name>
   <tag></tag>
   <elementGuidId>df8efe6f-5992-429e-9379-a63c50878268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-1119769200</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/article/div/main/div[1]/div/div[1]/form/div[3]/div[4]/div[2]/div[4]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9eff8e80-226f-4e37-9f02-e7c6ae9e9c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>c2466ed2-95cc-4368-8aaa-c74d4a2c7234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-1119769200</value>
      <webElementGuid>174fb425-f489-4cfc-86ef-26e602664997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_telefon</value>
      <webElementGuid>efd9c737-095b-417a-bfd0-009edc56098b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8564ddc3-c789-4c03-a009-e2cc5920db3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inputmask</name>
      <type>Main</type>
      <value>'mask': '+9(999)999-99-99'</value>
      <webElementGuid>ebded19a-f373-49ba-9f40-1887ea200199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>+_(___)___-__-__</value>
      <webElementGuid>676733f9-90e6-46a0-a6a0-3ed5b85cb6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58114965-2dc8-4aa7-9119-813c942a3712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-1119769200&quot;)</value>
      <webElementGuid>9df337e9-2267-492c-a310-2e2de568e02e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-1119769200']</value>
      <webElementGuid>590af2f6-be8d-4091-a320-683d71f67ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-148-need-help-form']/div[3]/div[4]/div[2]/div[4]/div/input</value>
      <webElementGuid>4cc3d0c6-2630-4d9c-a3a8-116b073a6255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>c0839d13-c40a-4dd1-9476-82c62fa58c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'leyka-1119769200' and @name = 'leyka_telefon' and @placeholder = '+_(___)___-__-__']</value>
      <webElementGuid>c6277fb0-ce3a-4fb3-985e-c2d929d34b77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
