<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__leyka_data</name>
   <tag></tag>
   <elementGuidId>dced49ce-0c75-4501-830d-c40d974eccea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-3101627350</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/article/div/main/div[1]/div/div[1]/form/div[3]/div[5]/div[2]/div[5]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce4938d5-936a-4657-a083-d30bf8259e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6afa9700-3161-406c-ac5e-4bafb1d3a650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-3101627350</value>
      <webElementGuid>38a98652-4a11-4231-8a08-f479f0ae2a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_data</value>
      <webElementGuid>af88107e-83a4-45ec-b3b4-2f9433bdcaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d4235b17-f0ca-4cb4-99a2-1d0c7e97ed80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inputmask</name>
      <type>Main</type>
      <value>'mask': '99.99.9999'</value>
      <webElementGuid>e75cfe08-c1ed-4a78-aafe-6936705d0e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29a4626c-35b7-496d-a260-f5cb14c1830c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-3101627350&quot;)</value>
      <webElementGuid>ec8650a4-48e5-4ca2-90e9-f00a7087ea9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-3101627350']</value>
      <webElementGuid>63fda179-1047-415f-9f70-7cdf83e11886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-118-star-form']/div[3]/div[4]/div[2]/div[5]/div/input</value>
      <webElementGuid>bedd154a-5b20-4ae6-8ee9-56404be3dc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>a4f2d33f-eb31-40e3-8b8e-a8491f204c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leyka-3101627350' and @name = 'leyka_data']</value>
      <webElementGuid>ec1f8bff-4927-4d85-b057-6de2ec535121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
