<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__leyka-default-submit</name>
   <tag></tag>
   <elementGuidId>f72363ec-6b90-4670-8c38-f1047e9631ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.leyka-default-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Пожертвовать']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5daee46-55e0-49f8-b315-a1dd447d8bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4ac3382d-3cf9-40c5-b360-4995729ad5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leyka-default-submit</value>
      <webElementGuid>360d8f6a-5b1f-45a3-852c-31cf7e54a6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Пожертвовать</value>
      <webElementGuid>3db4b3c4-9883-42af-b874-6162d51e60d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-submit-text-template</name>
      <type>Main</type>
      <value>Оформить ежемесячное пожертвование в #DAILY_ROUBLE_AMOUNT# ₽</value>
      <webElementGuid>eab8018d-085b-4f33-9e08-474db4ba915c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-pf-141-need-help-form&quot;)/div[@class=&quot;currency-tab currency-rub&quot;]/div[@class=&quot;section section--agreements&quot;]/div[@class=&quot;section__fields agreements&quot;]/div[@class=&quot;donor__submit&quot;]/input[@class=&quot;leyka-default-submit&quot;]</value>
      <webElementGuid>ad4bdf89-fa0c-471e-8f7a-6ef5f90261ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Пожертвовать']</value>
      <webElementGuid>2e1e20a6-3a9f-4192-a456-ab7be733f980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-141-need-help-form']/div[3]/div[5]/div/div[2]/input</value>
      <webElementGuid>1fe886b8-ec14-4ea9-b438-fb2c35eaca69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>b701d90c-896d-4ff6-8bd6-a703fc4bf315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>c933ca9f-7e06-4849-bdeb-fc4098992e17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
