<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email_leyka_donor_name</name>
   <tag></tag>
   <elementGuidId>76010a1d-5aa3-4687-a9b9-946271adf8e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-2452863822</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/article/div/main/div[1]/div/div[1]/form/div[3]/div[4]/div[2]/div[2]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7095b27-09ba-4bd5-bc09-70781eca23eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-2452863822</value>
      <webElementGuid>9d7066a8-8de1-46b0-95f7-73ad64de19f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>65b990bb-ec36-42cb-bf00-f8a38b0432c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_donor_name</value>
      <webElementGuid>332ea9ff-14f0-45b6-8fd3-e839943d4648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a39de147-048f-407c-9048-099dfa09489c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ваши имя и фамилия</value>
      <webElementGuid>29fa0caa-3925-401f-820f-315e0c8ac10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-2452863822&quot;)</value>
      <webElementGuid>17c4c216-5b32-4998-80ea-c1f42a7c32d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-2452863822']</value>
      <webElementGuid>fd513473-e6f5-4095-956d-4c3433da5cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-141-need-help-form']/div[3]/div[4]/div[2]/div[2]/label/input</value>
      <webElementGuid>765e3ade-bba3-46c4-aa2c-fd74b2cc3309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>bbb69251-7826-4bb7-9e75-8f2d1ee50c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'leyka-2452863822' and @type = 'text' and @name = 'leyka_donor_name' and @placeholder = 'Ваши имя и фамилия']</value>
      <webElementGuid>f64545ae-2c2c-41b3-bca2-2ef54224a7e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
