<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label__leyka-star-field-frame</name>
   <tag></tag>
   <elementGuidId>4333c2f6-9abe-4a1a-967a-980e1cd67917</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.leyka-star-field-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='leyka-pf-141-need-help-form']/div[3]/div[4]/div[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f63bd494-4110-4632-ac15-680ac5a0f8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leyka-star-field-frame</value>
      <webElementGuid>016f492a-5995-45e8-8b08-ed3c6c9f44fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-pf-141-need-help-form&quot;)/div[@class=&quot;currency-tab currency-rub&quot;]/div[@class=&quot;section section--person&quot;]/div[@class=&quot;section__fields donor equalize-elements-width&quot;]/div[@class=&quot;donor-field donor__textfield donor__textfield--email required&quot;]/label[@class=&quot;leyka-star-field-frame&quot;]</value>
      <webElementGuid>ed6945a2-e34f-4337-8a10-da533c48eb4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-141-need-help-form']/div[3]/div[4]/div[2]/div/label</value>
      <webElementGuid>a34e6511-c44c-4aab-8bde-8fed0b04ed4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Личные данные'])[1]/following::label[1]</value>
      <webElementGuid>925db8ee-1af7-4abf-b522-1ca9936ca992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='misplay'])[1]/following::label[1]</value>
      <webElementGuid>50370ced-08f0-45a1-a5c6-c8f82c801c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Укажите корректный адрес email'])[1]/preceding::label[1]</value>
      <webElementGuid>a75e775c-0262-4f65-8dcf-c543fbfe7f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Укажите ваше имя'])[1]/preceding::label[2]</value>
      <webElementGuid>821bd297-2a67-42f9-8009-fc9c791e9fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/label</value>
      <webElementGuid>7c98e845-8bac-49c8-ade0-f5923e4db7f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
