<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email_leyka_donor_name</name>
   <tag></tag>
   <elementGuidId>9483b1b2-9b48-4e26-bc65-7fb07c4731b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-1251413230</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;leyka-pf-148-need-help-form&quot;]/div[3]/div[4]/div[2]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>983a3ba8-86ce-4f4e-a97a-aaa629cdcde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-1251413230</value>
      <webElementGuid>00689134-4bb2-4c48-b93b-9e41181104ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77d0caf6-57b2-4a74-b1a1-97b828d2c77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_donor_name</value>
      <webElementGuid>ce57ca0b-82c7-4a33-a57a-37be9171088c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9503d436-3370-407e-b11c-238200e69fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ваши имя и фамилия</value>
      <webElementGuid>5810a097-074c-4025-85ae-b7ebc7c554b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-1251413230&quot;)</value>
      <webElementGuid>724957a9-05d8-451c-bf3c-901772d0551d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-1251413230']</value>
      <webElementGuid>459fd246-5215-48c5-afe1-05ff6dcb0138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-148-need-help-form']/div[3]/div[4]/div[2]/div[2]/label/input</value>
      <webElementGuid>4ac15aa6-dcb0-4bf6-af41-3a2911ca2624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>2c724aba-1972-4d90-94d3-60894337caf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'leyka-1251413230' and @type = 'text' and @name = 'leyka_donor_name' and @placeholder = 'Ваши имя и фамилия']</value>
      <webElementGuid>46663b1b-ab6a-4bb4-b84e-6e68be7e88a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
