<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__leyka_donor_email</name>
   <tag></tag>
   <elementGuidId>2417a907-b2f8-4f34-870d-2531f903a855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-2965969269</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;leyka-pf-148-need-help-form&quot;]/div[3]/div[4]/div[2]/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cf75b0f-eadb-46a9-898d-3f6efde34148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b25352b-4000-48c2-af09-2508860e7feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-2965969269</value>
      <webElementGuid>ee96903c-133a-451f-8e66-7c5e5d42d12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_donor_email</value>
      <webElementGuid>bf4081fe-eeb0-458d-811e-9c88bd3c2d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1f5de8fc-30fb-4ffd-aba4-b3b18480bfe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ваш email</value>
      <webElementGuid>c70bbb37-3e5f-4306-b0c9-4df2fcd2a8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-2965969269&quot;)</value>
      <webElementGuid>f55eb0f9-7fc5-4283-9cc3-35fd6560c98c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-2965969269']</value>
      <webElementGuid>b1357cfd-a0e0-4120-aac4-49f13a96b7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-148-need-help-form']/div[3]/div[4]/div[2]/div/label/input</value>
      <webElementGuid>a28ddb54-eb69-4edc-83f6-5413365065c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/label/input</value>
      <webElementGuid>1a996a28-fc66-4517-9002-ab42d5bc9a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leyka-2965969269' and @name = 'leyka_donor_email' and @placeholder = 'Ваш email']</value>
      <webElementGuid>fcb5b6d1-24f5-42c5-8506-eac382d29f2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
