<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email_leyka_donor_name</name>
   <tag></tag>
   <elementGuidId>c7270942-b5d9-4b84-ab71-30a76ce86317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leyka-1534778408</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leyka-1534778408']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc232941-c2e7-4532-939e-9e99917a3caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leyka-1534778408</value>
      <webElementGuid>b6c4bf64-50a3-4e82-a008-ad124f966be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>699a6869-931b-4576-9a27-36cb4bf4f8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leyka_donor_name</value>
      <webElementGuid>f9bb4a30-2bc4-43e8-9c4f-600c38c32b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fb35ecab-f4dc-4ceb-86e8-e60fbe33980d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ваши имя и фамилия</value>
      <webElementGuid>ce6bbf71-3bee-4502-94d7-88f6704a6508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leyka-1534778408&quot;)</value>
      <webElementGuid>a0bed767-0ddc-4bc2-b3b4-a6ec7d5511a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leyka-1534778408']</value>
      <webElementGuid>108e1dfa-838c-443b-82a0-4f7600f0c2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='leyka-pf-141-need-help-form']/div[3]/div[4]/div[2]/div[2]/label/input</value>
      <webElementGuid>916db8af-29a0-43c0-9169-aa70902c7a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>4355d5d7-1c76-4737-a6bd-c9c6d2709a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'leyka-1534778408' and @type = 'text' and @name = 'leyka_donor_name' and @placeholder = 'Ваши имя и фамилия']</value>
      <webElementGuid>19eda0ff-1b02-47a8-984b-94757724ede4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
